name: PR

on: [pull_request]

jobs:
  build_and_test:
    name: "Build and test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.15.x", "1.16.x", "1.17.x", "1.18.x", "1.19.x"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
      - run: cd v2
      - run: go get .
      - run: go build -v ./...
      - run: go test -v ./...
